<a href="https://colab.research.google.com/github/JColeman1550/BASEBALL/blob/main/2015_MLB_Data_Munging.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('chained_assignment', None)

In [3]:
%%capture
%pip install pybaseball
import pybaseball as pyb

In [5]:
 df_2015 = pyb.batting_stats(2015)

 df_2015 = df_2015.loc[:, :'WAR']

 df_2015.head()

,IDfg,Season,Name,Team,Age,G,AB,PA,H,1B,2B,3B,HR,R,RBI,BB,IBB,SO,HBP,SF,SH,GDP,SB,CS,AVG,GB,FB,LD,IFFB,Pitches,Balls,Strikes,IFH,BU,BUH,BB%,K%,BB/K,OBP,SLG,OPS,ISO,BABIP,GB/FB,LD%,GB%,FB%,IFFB%,HR/FB,IFH%,BUH%,wOBA,wRAA,wRC,Bat,Fld,Rep,Pos,RAR,WAR
0,11579,2015,Bryce Harper,WSN,22,153,521,654,172,91,38,1,42,118,99,124,15,131,5,4,0,15,6,4,0.330,151,154,87,9,2682,1180,1502,7,2,2,0.190,0.200,0.95,0.460,0.649,1.109,0.319,0.369,0.0098,0.222,0.385,0.393,0.058,0.273,0.046,1.000,0.461,77.3,151,74.1,-4.0,19.1,-6.1,87.8,9.3
3,10155,2015,Mike Trout,LAA,23,159,575,682,172,93,32,6,41,104,90,92,14,158,10,5,0,11,11,7,0.299,157,162,103,4,2980,1248,1732,20,0,0,0.135,0.232,0.58,0.402,0.590,0.991,0.290,0.344,0.0097,0.244,0.372,0.384,0.025,0.253,0.127,0.000,0.415,55.4,132,55.7,4.7,19.9,1.9,87.6,9.3
5,5038,2015,Josh Donaldson,TOR,29,158,620,711,184,100,41,2,41,122,123,73,0,133,6,10,2,16,6,0,0.297,222,188,86,18,2817,1119,1698,11,3,1,0.103,0.187,0.55,0.371,0.568,0.939,0.271,0.314,0.0118,0.173,0.448,0.379,0.096,0.218,0.050,0.333,0.398,47.9,128,44.7,8.6,20.8,1.5,82.1,8.7
1,4314,2015,Joey Votto,CIN,31,158,545,695,171,107,33,2,29,95,80,143,15,135,5,2,0,11,11,3,0.314,172,134,102,2,3020,1376,1644,3,4,2,0.206,0.194,1.06,0.459,0.541,1.000,0.228,0.371,0.0128,0.250,0.422,0.328,0.015,0.216,0.017,0.500,0.427,63.1,141,59.8,0.0,20.3,-11.8,68.3,7.3
2,9218,2015,Paul Goldschmidt,ARI,27,159,567,695,182,109,38,2,33,103,110,118,29,151,2,7,0,16,21,5,0.321,176,148,99,8,2917,1279,1638,11,0,0,0.170,0.217,0.78,0.435,0.570,1.005,0.249,0.382,0.0119,0.234,0.416,0.350,0.054,0.223,0.063,0.000,0.418,57.9,136,51.1,4.6,20.3,-12.1,68.1,7.2

In [6]:
df_2015.tail()

,IDfg,Season,Name,Team,Age,G,AB,PA,H,1B,2B,3B,HR,R,RBI,BB,IBB,SO,HBP,SF,SH,GDP,SB,CS,AVG,GB,FB,LD,IFFB,Pitches,Balls,Strikes,IFH,BU,BUH,BB%,K%,BB/K,OBP,SLG,OPS,ISO,BABIP,GB/FB,LD%,GB%,FB%,IFFB%,HR/FB,IFH%,BUH%,wOBA,wRAA,wRC,Bat,Fld,Rep,Pos,RAR,WAR
123,5760,2015,Avisail Garcia,CHW,24,148,553,601,142,110,17,2,13,66,59,36,3,141,8,4,0,13,7,7,0.257,203,111,102,7,2142,679,1463,22,0,0,0.060,0.235,0.26,0.309,0.365,0.675,0.108,0.320,0.0183,0.245,0.488,0.267,0.063,0.117,0.108,0.000,0.295,-8.5,59,-9.8,-0.4,17.6,-7.6,-2.9,-0.3
139,1433,2015,Wilson Ramos,WSN,27,128,475,504,109,78,16,0,15,41,68,21,2,101,0,8,0,16,0,0,0.229,212,95,75,6,1782,600,1182,10,0,0,0.042,0.200,0.21,0.258,0.358,0.616,0.128,0.256,0.0223,0.196,0.555,0.249,0.063,0.158,0.047,0.000,0.265,-19.6,37,-22.0,-5.6,14.7,9.1,-4.6,-0.5
97,7399,2015,Billy Butler,OAK,29,151,538,601,135,91,28,1,15,63,65,52,4,101,7,4,0,26,0,0,0.251,224,139,78,13,2248,807,1441,8,0,0,0.087,0.168,0.51,0.323,0.390,0.713,0.139,0.282,0.0161,0.177,0.508,0.315,0.094,0.108,0.036,0.000,0.311,-0.9,67,-1.6,0.3,17.6,-15.2,-7.9,-0.8
140,10030,2015,Chris Owings,ARI,23,147,515,552,117,81,27,5,4,59,43,26,3,144,1,3,7,9,16,4,0.227,143,124,96,11,1975,598,1377,10,18,7,0.047,0.261,0.18,0.264,0.322,0.587,0.095,0.305,0.0115,0.264,0.394,0.342,0.089,0.032,0.070,0.389,0.255,-25.8,36,-31.3,-3.5,16.1,2.9,-10.2,-1.1
128,5409,2015,Pablo Sandoval,BOS,28,126,470,505,115,79,25,1,10,43,47,25,1,73,7,2,1,14,0,0,0.245,195,129,75,17,1848,561,1287,8,1,0,0.050,0.145,0.34,0.292,0.366,0.658,0.121,0.270,0.0151,0.188,0.489,0.323,0.132,0.078,0.041,0.000,0.288,-10.3,47,-14.0,-10.4,14.8,1.8,-11.2,-1.2