<a href="https://colab.research.google.com/github/JColeman1550/BASEBALL/blob/main/2016_MLB_DATA_MUNGING.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('chained_assignment', None)

In [3]:
%%capture
%pip install pybaseball
import pybaseball as pyb

In [4]:
df_2016 = pyb.batting_stats(2016)

df_2016 = df_2016.loc[:, :'WAR']

df_2016.head()

,IDfg,Season,Name,Team,Age,G,AB,PA,H,1B,2B,3B,HR,R,RBI,BB,IBB,SO,HBP,SF,SH,GDP,SB,CS,AVG,GB,FB,LD,IFFB,Pitches,Balls,Strikes,IFH,BU,BUH,BB%,K%,BB/K,OBP,SLG,OPS,ISO,BABIP,GB/FB,LD%,GB%,FB%,IFFB%,HR/FB,IFH%,BUH%,wOBA,wRAA,wRC,Bat,Fld,Rep,Pos,RAR,WAR
1,10155,2016,Mike Trout,LAA,24,159,549,681,173,107,32,5,29,123,100,116,12,137,11,5,0,5,30,7,0.315,172,153,92,4,3014,1293,1721,18,0,0,0.170,0.201,0.85,0.441,0.550,0.991,0.235,0.371,0.0112,0.221,0.412,0.367,0.026,0.190,0.105,0.0,0.418,56.2,136,57.3,3.3,20.5,1.0,94.7,9.7
16,13611,2016,Mookie Betts,BOS,23,158,672,730,214,136,42,5,31,122,113,49,1,80,2,7,0,12,26,4,0.318,247,235,115,29,2709,989,1720,18,2,1,0.067,0.110,0.61,0.363,0.534,0.897,0.216,0.322,0.0105,0.193,0.414,0.394,0.123,0.132,0.073,0.5,0.379,36.9,123,31.2,21.1,22.0,-7.1,81.0,8.3
7,15429,2016,Kris Bryant,CHC,24,155,603,699,176,99,35,3,39,121,102,75,5,154,18,3,0,3,8,5,0.292,138,207,107,25,2699,1043,1656,18,0,0,0.107,0.220,0.49,0.385,0.554,0.939,0.262,0.332,0.0067,0.237,0.305,0.458,0.121,0.188,0.130,0.0,0.396,45.1,127,41.6,7.7,21.1,-1.4,76.8,7.9
4,5038,2016,Josh Donaldson,TOR,30,155,577,700,164,90,32,5,37,122,99,109,6,119,9,3,2,16,7,1,0.284,176,187,98,19,2952,1262,1690,8,2,0,0.156,0.170,0.92,0.404,0.549,0.953,0.265,0.300,0.0094,0.213,0.382,0.406,0.102,0.198,0.045,0.0,0.403,49.0,131,47.6,2.7,21.1,0.0,74.4,7.6
21,13624,2016,Corey Seager,LAD,22,157,627,687,193,122,40,5,26,105,72,54,5,133,4,2,0,12,3,3,0.308,229,145,121,3,2512,925,1587,8,1,0,0.079,0.194,0.41,0.365,0.512,0.877,0.204,0.355,0.0158,0.244,0.463,0.293,0.021,0.179,0.035,0.0,0.372,30.6,112,30.6,6.5,20.7,6.9,67.7,6.9

In [5]:
df_2016.tail()

,IDfg,Season,Name,Team,Age,G,AB,PA,H,1B,2B,3B,HR,R,RBI,BB,IBB,SO,HBP,SF,SH,GDP,SB,CS,AVG,GB,FB,LD,IFFB,Pitches,Balls,Strikes,IFH,BU,BUH,BB%,K%,BB/K,OBP,SLG,OPS,ISO,BABIP,GB/FB,LD%,GB%,FB%,IFFB%,HR/FB,IFH%,BUH%,wOBA,wRAA,wRC,Bat,Fld,Rep,Pos,RAR,WAR
98,3516,2016,Eric Hosmer,KCR,26,158,605,667,161,111,24,1,25,80,104,57,5,132,1,4,0,18,5,3,0.266,279,117,78,7,2563,967,1596,10,3,2,0.085,0.198,0.43,0.328,0.433,0.761,0.167,0.301,0.0238,0.165,0.589,0.247,0.060,0.214,0.036,0.667,0.326,4.4,83,1.8,-4.9,20.1,-12.0,2.3,0.2
116,10339,2016,Scooter Gennett,MIL,26,136,498,542,131,86,30,1,14,58,56,38,1,114,2,2,1,11,8,1,0.263,172,133,80,9,2069,720,1349,8,2,1,0.070,0.210,0.33,0.317,0.412,0.728,0.149,0.315,0.0129,0.208,0.447,0.345,0.068,0.105,0.047,0.500,0.315,-1.6,62,-5.3,-8.5,16.4,1.7,2.0,0.2
127,3086,2016,Mitch Moreland,TEX,30,147,460,503,107,64,21,0,22,49,60,35,5,118,8,0,0,8,1,0,0.233,142,128,72,14,1971,734,1237,10,0,0,0.070,0.235,0.30,0.298,0.422,0.720,0.189,0.266,0.0111,0.211,0.415,0.374,0.109,0.172,0.070,0.000,0.307,-4.4,55,-10.1,4.8,15.2,-9.8,0.2,0.0
134,2530,2016,Yonder Alonso,OAK,29,156,482,532,122,81,34,0,7,52,56,45,1,74,1,4,0,15,3,1,0.253,180,136,92,10,1883,729,1154,6,4,3,0.085,0.139,0.61,0.316,0.367,0.683,0.114,0.284,0.0132,0.225,0.441,0.333,0.074,0.051,0.033,0.750,0.299,-8.5,54,-8.2,0.8,16.1,-10.0,-1.9,-0.2
144,5133,2016,Alexei Ramirez,- - -,34,145,478,506,115,85,22,2,6,38,48,21,3,63,4,2,1,8,8,9,0.241,215,117,84,16,1840,600,1240,12,2,0,0.042,0.125,0.33,0.277,0.333,0.610,0.092,0.265,0.0184,0.202,0.517,0.281,0.137,0.051,0.056,0.000,0.264,-22.6,37,-23.3,-10.8,15.3,5.2,-15.5,-1.6